### ISSUE TITLE
fabric-shim incorrectly implements interface ChaincodeStub from fabric-shim-api

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-chaincode-node#292]
(copied from https://jira.hyperledger.org/browse/BE-882)

I'm using TS and just upgraded to the new 2.2.2 version of fabric-shim ; getting the following error:

 

node_modules/fabric-shim/types/index.d.ts:89:18 - error TS2420: Class 'import("fabric-shim").ChaincodeStub' incorrectly implements interface 'import("fabric-shim-api").ChaincodeStub'.
 Property 'getDateTimestamp' is missing in type 'import("fabric-shim").ChaincodeStub' but required in type 'import("fabric-shim-api").ChaincodeStub'.

89 export class ChaincodeStub implements IChaincodeStub {
 ~~~~~~~~~~~~~

node_modules/fabric-shim-api/types/index.d.ts:63:9
 63 getDateTimestamp(): Date;
 ~~~~~~~~~~~~~~~~~~~~~~~~~
 'getDateTimestamp' is declared here.

**Comment by greedyisgood** [comment]
Hi, after updating my fabric-shim and fabric-shim-api to 2.2.2, I still receive this error. May I know if this has been published to the latest? Thanks!
